### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by koenhendriks** [Comcast/sitemapper-for-js#2]
Getting the following error when running the script:

```

> xm-sitemap-generator@0.0.1 start /Users/koen/Code/sitemapper-for-js
> node server.js

App listening on port 8090
:: Queuing https://xxxxx/ ::
:: Data received for https://xxxxx/ ::
(node:18101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.notExemptions (/Users/koen/Code/sitemapper-for-js/utils/rules.js:36:50)
    at Object.doNotIgnore (/Users/koen/Code/sitemapper-for-js/utils/rules.js:58:21)
    at hrefs.forEach (/Users/koen/Code/sitemapper-for-js/utils/rules.js:27:22)
    at Array.forEach (<anonymous>)
    at Object.checkRules (/Users/koen/Code/sitemapper-for-js/utils/rules.js:25:15)
    at webService.getWeb.then (/Users/koen/Code/sitemapper-for-js/crawler.js:81:46)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:18101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iamssurya** [comment]
@koenhendriks Thanks for raising this issue. Would appreciate if you are interested to raise PR for the fix / we would work on this sooner to get this fixed

**Comment by koenhendriks** [comment]
I might find some time next month when I continue to work on a personal project, I'll let you know

**Comment by lmolteno** [comment]
I had to make sure my `config.js` file had a parameter for `ignoreStrings: []`, because it only checks the length of the array, and throws that error if it's not there.
